### PR TITLE
et-call-home-fqdn-policy: Begin using DNS proxy

### PR DESCRIPTION
**Pull request by raybejjani**
cilium provides a DNS proxy, and has disabled the DNS poller. Switch the
et-call-home-fqdn-policy monkey's policy to use the new proxy.

### CODE REVIEW

**Comment by tgraf** [comment]
Is this required or just coverage?

**Comment by raybejjani** [comment]
> Is this required or just coverage?
@tgraf I added handling for the slack hook as well.
Both are required unless we enable the DNS poller via CLI toggle (in our daemonset). The two changes exercise the proxy for both `matchName` and `matchPattern` rules.

**Comment by tgraf** [comment]
> Both are required unless we enable the DNS poller via CLI toggle (in our daemonset). The two changes exercise the proxy for both `matchName` and `matchPattern` rules.

Shouldn't leaving out the rules section whitelist all DNS requests?

**Comment by tgraf** [comment]
@raybejjani I'm still a bit confused. The rule as it stood before, worked in 1.3. It no longer works with 1.4. Why?

**Comment by raybejjani** [comment]
Because we disabled the DNS poller as a default behaviour in master/1.4 (in the https://github.com/cilium/cilium/pull/5641 PR). To get that behaviour back, we would need to add `--fqdn-enable-poller` to the daemonset we're testing with (the poller hasn't changed beyond the default disable). 
Previously, the rule worked (with some exceptions) because the poller would poll for toFQDNs.matchName and trigger the correct rule generation. Without the poller the proxy is the only other source of these events.

PS Since you will ask this next: It was requested that I disable the poller by default. Then it was requested that I leave it enabled. I asked that the people in the same timezone decide what the preference was without me.

**Pull request merged**
